In [2]:
import seaborn as sns
import pandas as pd
import numpy as np

data = sns.load_dataset('iris')
print('Original Dataset')
data.head()

Original Dataset


sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [3]:
x = data.iloc[:,:4].values
y = data['species'].values

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [15]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2,random_state=42)

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [17]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(x_train, y_train)

GaussianNB()

In [18]:
y_pred = classifier.predict(x_test) 

In [19]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import accuracy_score,auc,f1_score,precision_score,recall_score
print ("Accuracy : ", accuracy_score(y_test, y_pred))

Accuracy :  1.0


In [20]:
df = pd.DataFrame({'Real Values':y_test, 'Predicted Values':y_pred})
df

Real Values Predicted Values
0   versicolor       versicolor
1       setosa           setosa
2    virginica        virginica
3   versicolor       versicolor
4   versicolor       versicolor
5       setosa           setosa
6   versicolor       versicolor
7    virginica        virginica
8   versicolor       versicolor
9   versicolor       versicolor
10   virginica        virginica
11      setosa           setosa
12      setosa           setosa
13      setosa           setosa
14      setosa           setosa
15  versicolor       versicolor
16   virginica        virginica
17  versicolor       versicolor
18  versicolor       versicolor
19   virginica        virginica
20      setosa           setosa
21   virginica        virginica
22      setosa           setosa
23   virginica        virginica
24   virginica        virginica
25   virginica        virginica
26   virginica        virginica
27   virginica        virginica
28      setosa           setosa
29      setosa           setosa

In [13]:
from sklearn.metrics import accuracy_score

accuracy_score = accuracy_score(y_test, y_pred) 
print (accuracy_score)

1.0


In [21]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test,y_pred)
print('Confusion Matrix: ')
print(cm)   
ac1 = accuracy_score(y_test, y_pred)*100
print('Accuracy Score:')
print(ac1)

Confusion Matrix: 
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Accuracy Score:
100.0


In [24]:
print("----------For Setosa----------")
tp=cm[0][0]
fn=(cm[0][1])+(cm[0][2])
tn=(cm[1][1])+(cm[1][2])+(cm[2][1])+(cm[2][2])
fp=(cm[1][0])+(cm[2][0])
print('true positive: ',tp)
print('false positive: ',fp)
print('true negative: ',tn)
print('false negative: ',fn)
error_rate=(fp+fn)/(tp+tn+fp+fn)
print('error rate:', error_rate )

----------For Setosa----------
true positive:  10
false positive:  0
true negative:  20
false negative:  0
error rate: 0.0


In [25]:
print("----------For Versicolor----------")
tp=cm[1][1]
fn=(cm[1][0])+(cm[1][2])
tn=(cm[0][0])+(cm[0][2])+(cm[2][0])+(cm[2][2])
fp=(cm[0][1])+(cm[2][1])
print('true positive: ',tp)
print('false positive: ',fp)
print('true negative: ',tn)
print('false negative: ',fn)
error_rate=(fp+fn)/(tp+tn+fp+fn)
print('error rate:', error_rate )

----------For Versicolor----------
true positive:  9
false positive:  0
true negative:  21
false negative:  0
error rate: 0.0


In [26]:
print("----------For Verginica----------")
tp=cm[1][2]
fn=(cm[2][0])+(cm[2][1])
tn=(cm[0][0])+(cm[0][1])+(cm[1][0])+(cm[1][1])
fp=(cm[0][2])+(cm[1][2])
print('true positive: ',tp)
print('false positive: ',fp)
print('true negative: ',tn)
print('false negative: ',fn)
error_rate=(fp+fn)/(tp+tn+fp+fn)
print('error rate:', error_rate )

----------For Verginica----------
true positive:  0
false positive:  0
true negative:  19
false negative:  0
error rate: 0.0
